### ISSUE TITLE
Pre-release checklist

### ISSUE THREAD

**Issue by SijmenHuizenga** [SijmenHuizenga/future-of-tech#1]
- [x] Google Captcha
- [x] Show example predictions
- [x] Write & Show FAQ
- [x] Spellcheck
- [x] Favicon
- [x] Page description + social media preview
